apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          imagePullPolicy: {{ .Values.nginx.imagePullPolicy }}

          ports:
            - containerPort: {{ .Values.nginx.service.targetPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.nginx.service.type }}

  selector:
    app: nginx

  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}